version: 2.0

jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: cibuilds/hugo:latest

    steps:
      - checkout

      - run:
          name: Get latest scientific-python.org
          command: |
            mkdir -p /tmp
            git clone https://github.com/scientific-python/scientific-python.org.git /tmp/scientific-python.org

      - run:
          name: Embed specs in scientific-python.org
          command: |
            git -C /tmp/scientific-python.org submodule update --init
            rm -rf /tmp/scientific-python.org/content/specs/*
            cp -r ./* /tmp/scientific-python.org/content/specs

      - run:
          # TODO: include --buildDrafts?
          name: Build site
          command: |
            cd /tmp/scientific-python.org
            sed -i '/theme/a uglyurls = true' config.toml
            sed -i 's/\"\/\"/\"\/index.html\"/g' config.toml
            sed -i 's/\/about/\/about.html/g' config.toml
            sed -i 's/\/posts/\/posts.html/g' config.toml
            sed -i 's/\/specs/\/specs.html/g' config.toml
            sed -i 's/\/summits/\/summits.html/g' config.toml
            hugo

      - store_artifacts:
          path: /tmp/scientific-python.org/public/
