[[item]]
type = 'card'
classcard = 'text-center'
body = '''{{< image
  src="https://avatars.githubusercontent.com/u/13301940?u=aa3bac002007d5212fe22a0baaadc25e078474ca&v=4"
  alt="Avatar of Anderson Banihirwe"
>}}
Anderson Banihirwe'''
link = 'https://github.com/andersy005'

[[item]]
type = 'card'
classcard = 'text-center'
body = '''{{< image
    src="https://avatars.githubusercontent.com/u/7579677?u=1ebcc2526a9787b4786c9383870c6b8fbad217d8&v=4"
    alt="Avatar of Georgiana"
>}}
Georgiana'''
link = 'https://github.com/GeorgianaElena'

[[item]]
type = 'card'
classcard = 'text-center'
body = '''{{< image
  src="https://avatars.githubusercontent.com/u/13029839?u=672ad3a5d17cec4ec6ff4a4b3302a4bef9535c8b&v=4"
  alt="Avatar of Julien Jerphanion"
>}}
Julien Jerphanion'''
link = 'https://github.com/jjerphan'

[[item]]
type = 'card'
classcard = 'text-center'
body = '''{{< image
  src="https://avatars.githubusercontent.com/u/492549?v=4"
  alt="Avatar of Juan Nunez-Iglesias"
>}}
Juan Nunez-Iglesias'''
link = 'https://github.com/jni'

[[item]]
type = 'card'
classcard = 'text-center'
body = '''{{< image
    src="https://avatars.githubusercontent.com/u/1020496?u=c30d768880284601483689157e4114351815044b&v=4"
    alt="Avatar of Joris Van den Bossche"
>}}
Joris Van den Bossche'''
link = 'https://github.com/jorisvandenbossche'

[[item]]
type = 'card'
classcard = 'text-center'
body = '''{{< image
    src="https://avatars.githubusercontent.com/u/29165011?u=a9cad2941ed8ddec88ea9fc7523ff70433fce7e6&v=4"
    alt="Avatar of Kira Evans"
>}}
Kira Evans'''
link = 'https://github.com/kne42'

[[item]]
type = 'card'
classcard = 'text-center'
body = '''{{< image
    src="https://avatars.githubusercontent.com/u/3487237?v=4"
    alt="Avatar of Kristen Thyng"
>}}
Kristen Thyng'''
link = 'https://github.com/kthyng'

[[item]]
type = 'card'
classcard = 'text-center'
body = '''{{< image
  src="https://avatars.githubusercontent.com/u/23182829?u=847be7a6e1eb5d5198d61c7f5ae093d11f2f9763&v=4"
  alt="Avatar of Lucy Liu"
>}}
Lucy Liu'''
link = 'https://github.com/lucyleeow'

[[item]]
type = 'card'
classcard = 'text-center'
body = '''{{< image
  src="https://avatars.githubusercontent.com/u/3949932?u=aacac68df60d2cf64c17c7e5aa17adf8b738aa7b&v=4"
  alt="Avatar of Melissa Weber Mendonça"
>}}
Melissa Weber Mendonça'''
link = 'https://github.com/melissawm'

[[item]]
type = 'card'
classcard = 'text-center'
body = '''{{< image
  src="https://avatars.githubusercontent.com/u/2090236?v=4"
  alt="Avatar of P. L. Lim"
>}}
P. L. Lim'''
link = 'https://github.com/pllim'
